apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "couchdb.fullname" . }}-config
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
data:
  local.ini: |
    [couchdb]
    single_node = {{ .Values.couchdb.config.singleNode }}
    
    [chttpd]
    port = {{ .Values.service.port }}
    bind_address = 0.0.0.0
    
    [httpd]
    {{- if .Values.couchdb.config.security.requireValidUser }}
    require_valid_user = {{ .Values.couchdb.config.security.requireValidUser }}
    {{- end }}
    
    [log]
    level = {{ .Values.couchdb.config.logLevel }}
    
    [admins]
    {{ .Values.couchdb.admin.username }} = {{ randAlphaNum 32 }}
