{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "couchdb.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingress.from }}
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.couchdb.config.https.enabled }}
        - protocol: TCP
          port: {{ .Values.couchdb.config.https.port }}
        {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        {{- if .Values.networkPolicy.egress.to }}
        {{- toYaml .Values.networkPolicy.egress.to | nindent 8 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.couchdb.config.https.enabled }}
        - protocol: TCP
          port: {{ .Values.couchdb.config.https.port }}
        {{- end }}
  {{- end }}
{{- end }}
