apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.couchdb.config.https.enabled }}
    - port: {{ .Values.couchdb.config.https.port }}
      targetPort: {{ .Values.couchdb.config.https.port }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "couchdb.selectorLabels" . | nindent 4 }}
