apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  namespace: argocd
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/instance: couchdb
    app.kubernetes.io/managed-by: ArgoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/votre-username/couchdb-k8s.git
    targetRevision: HEAD
    path: helm/couchdb
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: couchdb.admin.existingSecret
          value: "couchdb-secrets"
        - name: couchdb.database.existingSecret
          value: "couchdb-secrets"
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: "20Gi"
        - name: couchdb.config.security.requireValidUser
          value: "true"
        - name: couchdb.config.security.httpsOnly
          value: "false"
        - name: networkPolicy.enabled
          value: "true"
        - name: podDisruptionBudget.enabled
          value: "true"
        - name: resources.limits.cpu
          value: "1000m"
        - name: resources.limits.memory
          value: "2Gi"
        - name: resources.requests.cpu
          value: "500m"
        - name: resources.requests.memory
          value: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: kk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
