# RBAC configuration for CouchDB
apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchdb-sa
  namespace: kk
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/instance: couchdb
    app.kubernetes.io/managed-by: ArgoCD
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kk
  name: couchdb-role
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/instance: couchdb
    app.kubernetes.io/managed-by: ArgoCD
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: couchdb-rolebinding
  namespace: kk
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/instance: couchdb
    app.kubernetes.io/managed-by: ArgoCD
subjects:
- kind: ServiceAccount
  name: couchdb-sa
  namespace: kk
roleRef:
  kind: Role
  name: couchdb-role
  apiGroup: rbac.authorization.k8s.io
